#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from babel import Locale

locale = Locale('ru')

databrowser_countries = ['Oil Producing Regions',
                         'MZM_NSE','MZM_CRB','MZM_PRG',
                         'Groups of Nations',
                         'MZM_WORLD','BP_FSU','MZM_EU0','MZM_EU1','MZM_OPEC','MZM_OECD','MZM_G7','MZM_O5','MZM_G75',
                         '003', # North America
                         'US','CA','MX','MZM_NAM',
                         '005' # South America
                         'AR','BO','BR','CL','CO','EC','PE','TT','VE',
                         '150' # Europe
                         'AT','AZ','BY','BP_BELUX','BG','CZ','DK','FI','FR','DE','GR',
                         'HIS','IE','IT','KZ','LT','NL','NO','PL','PT','RO','RU','SK',
                         'ES','SE','CH','TR','TM','UA','GB','UZ',
                         'Middle East'
                         'BH','IR','IQ','KW','OM','QA','SY','YE','AE','BP_TME',
                         '002' # Africa
                         'DZ','AO','CM','TD','CG','EG','GQ','GA','LY','NG','SD','TN','ZA','ZW',
                         'Asia Pacific'
                         'AU','BN','BD','CN','BP_HK','IN','ID','JP','MM','MY','NZ','PK','PH','SG','KR','TW','TH','VN']


print('                  <select id="countryID" name="countryID">')
print('')
print('                    <optgroup label="***Groups of Nations***">')
print('                      <option selected value="MZM_WORLD">' + locale.territories['001'] + '</option>')
print('                      <option value="MZM_FSU">***Former Soviet Union***</option>')
print('                      <option value="MZM_EU0">' + locale.territories['150'] + ' ***(-FSU)***</option>')
print('                      <option value="MZM_EU1">' + locale.territories['150'] + ' ***(+FSU)***</option>')
print('                      <option value="MZM_OPEC10">***OPEC10***</option>')
print('                      <option value="MZM_OPEC">***OPEC***</option>')
print('                      <option value="MZM_NON_OPEC">***Non-OPEC***</option>')
print('                      <option value="MZM_OECD">***OECD***</option>')
print('                      <option value="MZM_G7">G7</option>')
print('                      <option value="MZM_O5">O5</option>')
print('                      <option value="MZM_G75">G7 + O5</option>')
print('                    </optgroup>')
print('')
print('                    <optgroup label="***Oil Producing Regions***">')
print('                      <option value="MZM_NSE">***North Sea***</option>')
print('                      <option value="MZM_CRB">' + locale.territories['029'] + '</option>')
print('                      <option value="MZM_PRG">***Persian Gulf***</option>')
print('                      <option value="MZM_WAF">***West Africa***</option>')
print('                    </optgroup>')
print('')
print('                    <optgroup label="' + locale.territories['003'] + '">')
print('                      <option value="MZM_TNA">Total ' + locale.territories['003'] + '</option>')
print('                      <option value="US">' + locale.territories['US'] + '</option>')
print('                      <option value="CA">' + locale.territories['CA'] + '</option>')
print('                      <option value="MX">' + locale.territories['MX'] + '</option>')
print('                    </optgroup>')
print('')
print('                    <optgroup label="' + locale.territories['005'] + '">')
print('                      <option value="MZM_TSCA">Total ' + locale.territories['005'] + '</option>')
print('                      <option value="AR">' + locale.territories['AR'] + '</option>')
print('                      <option value="BO">' + locale.territories['BO'] + '</option>')
print('                      <option value="BR">' + locale.territories['BR'] + '</option>')
print('                      <option value="CL">' + locale.territories['CL'] + '</option>')
print('                      <option value="CO">' + locale.territories['CO'] + '</option>')
print('                      <option value="EC">' + locale.territories['EC'] + '</option>')
print('                      <option value="PE">' + locale.territories['PE'] + '</option>')
print('                      <option value="TT">' + locale.territories['TT'] + '</option>')
print('                      <option value="VE">' + locale.territories['VE'] + '</option>')
print('                    </optgroup>')
print('')
print('                    <optgroup label="' + locale.territories['150'] + ' & Eurasia">')
print('                      <option value="MZM_TEE">Total ' + locale.territories['150'] + '</option>')
print('                      <option value="AT">' + locale.territories['AT'] + '</option>')
print('                      <option value="AZ">' + locale.territories['AZ'] + '</option>')
print('                      <option value="BY">' + locale.territories['BY'] + '</option>')
print('                      <option value="MZM_BELU">' + locale.territories['BE'] + ' & ' + locale.territories['LU'] + '</option>')
print('                      <option value="BG">' + locale.territories['BG'] + '</option>')
print('                      <option value="CZ">' + locale.territories['CZ'] + '</option>')
print('                      <option value="DK">' + locale.territories['DK'] + '</option>')
print('                      <option value="FI">' + locale.territories['FI'] + '</option>')
print('                      <option value="FR">' + locale.territories['FR'] + '</option>')
print('                      <option value="DE">' + locale.territories['DE'] + '</option>')
print('                      <option value="GR">' + locale.territories['GR'] + '</option>')
print('                      <option value="HU">' + locale.territories['HU'] + '</option>')
print('                      <option value="IS">' + locale.territories['IS'] + '</option>')
print('                      <option value="IE">' + locale.territories['IE'] + '</option>')
print('                      <option value="IT">' + locale.territories['IT'] + '</option>')
print('                      <option value="KZ">' + locale.territories['KZ'] + '</option>')
print('                      <option value="LT">' + locale.territories['LT'] + '</option>')
print('                      <option value="NL">' + locale.territories['NL'] + '</option>')
print('                      <option value="NO">' + locale.territories['NO'] + '</option>')
print('                      <option value="PL">' + locale.territories['PL'] + '</option>')
print('                      <option value="PT">' + locale.territories['PT'] + '</option>')
print('                      <option value="RO">' + locale.territories['RO'] + '</option>')
print('                      <option value="RU">' + locale.territories['RU'] + '</option>')
print('                      <option value="SK">' + locale.territories['SK'] + '</option>')
print('                      <option value="ES">' + locale.territories['ES'] + '</option>')
print('                      <option value="SE">' + locale.territories['SE'] + '</option>')
print('                      <option value="CH">' + locale.territories['CH'] + '</option>')
print('                      <option value="TR">' + locale.territories['TR'] + '</option>')
print('                      <option value="TM">' + locale.territories['TM'] + '</option>')
print('                      <option value="UA">' + locale.territories['UA'] + '</option>')
print('                      <option value="GB">' + locale.territories['GB'] + '</option>')
print('                      <option value="UZ">' + locale.territories['UZ'] + '</option>')
print('                    </optgroup>')
print('')
print('                    <optgroup label="***Middle East***">')
print('                      <option value="MZM_TME">***Total Middle East***</option>')
print('                      <option value="BH">' + locale.territories['BH'] + '</option>')
print('                      <option value="IR">' + locale.territories['IR'] + '</option>')
print('                      <option value="IQ">' + locale.territories['IQ'] + '</option>')
print('                      <option value="KW">' + locale.territories['KW'] + '</option>')
print('                      <option value="OM">' + locale.territories['OM'] + '</option>')
print('                      <option value="QA">' + locale.territories['QA'] + '</option>')
print('                      <option value="SA">' + locale.territories['SA'] + '</option>')
print('                      <option value="SY">' + locale.territories['SY'] + '</option>')
print('                      <option value="YE">' + locale.territories['YE'] + '</option>')
print('                      <option value="AE">' + locale.territories['AE'] + '</option>')
print('                    </optgroup>')
print('')
print('                    <optgroup label="' + locale.territories['002'] + '">')
print('                      <option value="MZM_TAF">Total ' + locale.territories['002'] + '</option>')
print('                      <option value="DZ">' + locale.territories['DZ'] + '</option>')
print('                      <option value="AO">' + locale.territories['AO'] + '</option>')
print('                      <option value="CM">' + locale.territories['CM'] + '</option>')
print('                      <option value="TD">' + locale.territories['TD'] + '</option>')
print('                      <option value="CG">' + locale.territories['CG'] + '</option>')
print('                      <option value="EG">' + locale.territories['EG'] + '</option>')
print('                      <option value="GQ">' + locale.territories['GQ'] + '</option>')
print('                      <option value="GA">' + locale.territories['GA'] + '</option>')
print('                      <option value="LY">' + locale.territories['LY'] + '</option>')
print('                      <option value="NG">' + locale.territories['NG'] + '</option>')
print('                      <option value="SD">' + locale.territories['SD'] + '</option>')
print('                      <option value="TN">' + locale.territories['TN'] + '</option>')
print('                      <option value="ZA">' + locale.territories['ZA'] + '</option>')
print('                      <option value="ZW">' + locale.territories['ZW'] + '</option>')
print('                    </optgroup>')
print('')
print('                    <optgroup label="***Asia Pacific***">')
print('                      <option value="MZM_TAP">***Total Asia Pacific***</option>')
print('                      <option value="AU">' + locale.territories['AU'] + '</option>')
print('                      <option value="BN">' + locale.territories['BN'] + '</option>')
print('                      <option value="BD">' + locale.territories['BD'] + '</option>')
print('                      <option value="CN">' + locale.territories['CN'] + '</option>')
print('                      <option value="HK">' + locale.territories['HK'] + '</option>')
print('                      <option value="IN">' + locale.territories['IN'] + '</option>')
print('                      <option value="ID">' + locale.territories['ID'] + '</option>')
print('                      <option value="JP">' + locale.territories['JP'] + '</option>')
print('                      <option value="MM">' + locale.territories['MM'] + '</option>')
print('                      <option value="MY">' + locale.territories['MY'] + '</option>')
print('                      <option value="NZ">' + locale.territories['NZ'] + '</option>')
print('                      <option value="PK">' + locale.territories['PK'] + '</option>')
print('                      <option value="PH">' + locale.territories['PH'] + '</option>')
print('                      <option value="SG">' + locale.territories['SG'] + '</option>')
print('                      <option value="KR">' + locale.territories['KR'] + '</option>')
print('                      <option value="TW">' + locale.territories['TW'] + '</option>')
print('                      <option value="TH">' + locale.territories['TH'] + '</option>')
print('                      <option value="VN">' + locale.territories['VN'] + '</option>')
print('                    </optgroup>')
print('')
print('                  </select>')
